Models/Hobby.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace BeltExam.Models
{
    public class Hobby
    {
        [Key]
        public int HobbyId {get;set;}
        [Required]
        [Display(Name="Name: ")]
        public string HobbyName {get; set;}
        [Required]
        [MinLength(10)]
        [Display(Name="Description: ")]
        public string Description {get; set;}

        public DateTime CreatedAt {get; set;} = DateTime.Now;
        public DateTime UpdatedAt {get; set;} = DateTime.Now;

        public List<Association> Enthusiasts {get;set;}
        

    }
}

Controllers/HobbyController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BeltExam.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace BeltExam.Controllers
{
    [Route("hobbys")]
    public class HobbyController : Controller
    {
        private HomeContext dbContext;
        public HobbyController(HomeContext context)
        {
            dbContext = context;
        }

        [HttpGet("dashboard")]
        public IActionResult Dashboard()
        {
            if(HttpContext.Session.GetString("UserName") == null)
          {
              return RedirectToAction("LogOut", "Home");
          }
          else
          {
              User userInDb = dbContext.Users.Include(u => u.CoolHobbies).FirstOrDefault(u => u.UserName == HttpContext.Session.GetString("UserName"));
              ViewBag.User = userInDb;

              List<Hobby> AllHobbies = dbContext.Hobbies.Include(h => h.Enthusiasts).ThenInclude(a => a.Fan).ToList();
              return View(AllHobbies);
          }
        }

        [HttpGet("new")]
        public IActionResult New()
        {
            if(HttpContext.Session.GetString("UserName") == null)
            {
                return RedirectToAction("LogOut", "Home");
            }
            else
            {
                User userInDb = dbContext.Users.Include(u => u.CoolHobbies).FirstOrDefault(u => u.UserName == HttpContext.Session.GetString("UserName"));
                ViewBag.User = userInDb;
                return View();
            }
        }

        [HttpPost("create")]
        public IActionResult Create(Hobby hob)
        {
            if(HttpContext.Session.GetString("UserName") == null)
            {
                return RedirectToAction("LogOut", "Home");
            }
            else
            {
                if(ModelState.IsValid)
                {
                    dbContext.Hobbies.Add(hob);
                    dbContext.SaveChanges();
                    return Redirect($"Show/{hob.HobbyId}");
                }
                else
                {
                    User userInDb = dbContext.Users.Include(u => u.CoolHobbies).FirstOrDefault(u => u.UserName == HttpContext.Session.GetString("UserName"));
                    ViewBag.User = userInDb;
                    return View("New");
                }
            }
        }

        [HttpGet("show/{hobbyId}")]
        public IActionResult Show(int hobbyId)
        {
            if(HttpContext.Session.GetString("UserName") == null)
            {
                return RedirectToAction("LogOut", "Home");
            }
            else
            {
                User userInDb = dbContext.Users.Include(u => u.CoolHobbies).FirstOrDefault(u => u.UserName == HttpContext.Session.GetString("UserName"));
                ViewBag.User = userInDb;

                Hobby show = dbContext.Hobbies.Include(h => h.Enthusiasts).ThenInclude(a => a.Fan).FirstOrDefault(u => u.HobbyId == hobbyId);
                ViewBag.Fans = dbContext.Hobbies;
                return View(show);
            }
        }

        [HttpGet("cool/{hobbyId}/{userId}/{status}")]

        public IActionResult AddHobby(int hobbyId, int userId, string status)
        {
            if(HttpContext.Session.GetString("UserName") == null)
            {
                return RedirectToAction("LogOut", "Home");
            }
            else
            {
                if(status == "add")
                {
                    Association join = new Association();
                    join.HobbyId = hobbyId;
                    join.UserID = userId;
                    dbContext.Associations.Add(join);
                    dbContext.SaveChanges();
                }

                return RedirectToAction("Dashboard");
            }
        }



    }
}

Views/Hobby/Dashboard.cshtml
@model  List<Hobby>

<h1> Your Hobbies</h1>
<a asp-action="LogOut" asp-controller="Home" class="btn btn-danger">LogOut</a>

<table class="table table-hover">
    <thead>
    <tr>
        <td>Name</td>
        <td>Enthusiasts</td>
    </tr>
    </thead>
    <tbody>
        @foreach(var h in Model)
        {
            <tr>
                <td><a asp-action="Show" asp-controller="Hobby" asp-route-hobbyId="@h.HobbyId">@h.HobbyName</a></td>
                <td>@h.Enthusiasts.Count</td>
            </tr>
        }
    </tbody>
</table>

<a asp-action="New" asp-controller="Hobby" class="btn btn-warning">Create new Hobby</a>

Views/Hobby/New.cshtml
@model Hobby

<h1>Create a Hobby</h1>
<a asp-action="Dashboard" asp-controller="Hobby">Home</a>
<a asp-action="LogOut" asp-controller="Home" class="btn btn-danger">LogOut</a>

<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="Create" asp-controller="Hobby" method="POST">
    <label asp-for="HobbyName"></label>
    <input asp-for="HobbyName"><br>

    <label asp-for="Description"></label>
    <input asp-for="Description"><br>
    <input type="submit" value="Create" class="btn btn-outline-warning">

</form>

Views/Hobby/Show.cshtml
@model Hobby

<h1>@Model.HobbyName</h1>
<a asp-action="LogOut" asp-controller="Home" class="btn btn-danger">LogOut</a>
<a asp-action="Dashboard" asp-controller="Hobby">Home</a>


<h4>Description: </h4>
<h6>@Model.Description</h6>

<h4>@Model.HobbyName: Enthusiasts </h4>
@foreach(var e in @Model.Enthusiasts)
{
    <ul>
        <li>@e.Fan.FirstName</li>
    </ul>
}

<h5>Become an Enthusiasts!! </h5>
@if(Model.Enthusiasts.All(s => s.UserID == @ViewBag.User.UserID))
{
 <a asp-action="AddHobby" asp-controller="Hobby" asp-route-hobbyId="@Model.HobbyId" asp-route-userId="@ViewBag.User.UserID" asp-route-status="add">Add to hobbies</a>
}